title: Teddy Koker
# description: >- # this means to ignore newlines until "baseurl:"
#  Machine Learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://teddykoker.com" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: UA-138897125-1
permalink: /:categories/:year/:month/:title/
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# syntax highlighting
highlighter: rouge

# for brave verification
include: [".well-known"]
